on: push

jobs:
  approve_pull_requests:
    runs-on: ubuntu-latest
    env: 
      APPROVE_BOT_NAME: ${{secrets.APPROVE_BOT_NAME}}
      APPROVE_BOT_EMAIL: ${{secrets.APPROVE_BOT_EMAIL}}
      BRANCH_NAME: "new-translations"
    steps:
      - name: Set Loc bot config details
        run: |
          git config --global user.name $APPROVE_BOT_NAME
          git config --global user.email $APPROVE_BOT_EMAIL
          git config --global core.ignorecase true
      - uses: crazy-max/ghaction-import-gpg@v4
        id: import-gpg
        with:
          gpg_private_key: ${{ secrets.GPG_TOKEN }}
          passphrase: ${{ secrets.PASS_PHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Approve pull requests
        run: |
          mainFolder=$PWD
          for folder in visuals/*; do
            repoName=$(echo $folder| cut -d'/' -f 2)
            echo "::group::Approve and merge to $repoName"  
              cd "$mainFolder/$folder"
              pullRequestNumber=$(gh search prs --repo=microsoft/$repoName --state=open --head=$BRANCH_NAME --json number)
              if [[ $pullRequestNumber == "[]" ]]; then
                echo "No pull request for $repoName"
                continue
              fi
              emptyChanges='{"additions":0,"deletions":0}'
              changes=$(gh pr view --json additions,deletions)
              if [[ $changes == $emptyChanges ]]; then
                echo "No changes for $repoName"
                continue
              fi
              gh pr review --approve
              echo "Pull request to $repoName was approved"
              # gh pr merge -s --auto
              echo "Pull request to $repoName was merged"
            echo "::endgroup::"
          done;
        env:
          GITHUB_TOKEN: ${{ secrets.APPROVE_TOKEN }}