name: CI

on: [push, pull_request]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
    - name: Get all dirs
      run: |
        ls
        cd ..
        ls
        cd ..
        ls
        cd ..
        ls
    - name: Install packages
      run: npm install
    - name: Run test
      run: npm run capabilitiesToResources