name: Tests

on: [push]

jobs:
  validateJsons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install packages
        run: npm ci
      - name: Run validateJsons
        run: npm run validateJsons
  