name: Tests

on: [push]

jobs:
  validateJsons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install packages
        run: npm i
      - name: Run validateJsons
        run: npm run validateJsons
  validateTranslations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/labeler@v2
        env:
          token: ${{ github.token }}
      - name: Install packages
        run: npm i
      - name: Run
        run: npm run validateTranslations
  