name: CI

on: [push, pull_request]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
    - name: Run a multi-line script
      run: |
        cd ..
        ls
        npm install
        npm run capabilitiesToResources