on: push

jobs:
  update_translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false
          token: ${{ secrets.TOKEN }}
      - name: Set config details
        run: |
          git config --global user.name 'pbcvloc'
          git config --global user.email 'pbcvloc@microsoft.com'
          git config core.ignorecase true
      - uses: crazy-max/ghaction-import-gpg@v4
        id: import-gpg
        with:
          gpg_private_key: ${{ secrets.GPG_TOKEN }}
          passphrase: ${{ secrets.PASS_PHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Update submodules
        run: |
          git pull --recurse-submodules
          git submodule update --init --recursive --remote
      - name: Update remote links
        run: |
          mainFolder=$PWD
          git remote remove origin
          git remote add origin "https://pbcvloc:${{secrets.TOKEN}}@github.com/microsoft/powerbi-visuals-utils-localizationutils.git"
          for folder in visuals/*; do
            repoName=$(echo $folder| cut -d'/' -f 2)
            cd "$mainFolder/$folder"
            git remote remove origin
            git remote add origin https://pbcvloc:${{secrets.TOKEN}}@github.com/microsoft/$repoName.git
            echo "$repoName updated"
            git checkout new-translations >/dev/null || git checkout -b new-translations
          done;
          cd "$mainFolder"
          git add . && git commit -S -m "New translation" >/dev/null && git push || echo "No submodule updates"
      - name: Copy EN translation
        run: |
          for file in ./visuals/*/stringResources/en-US/resources.resjson; do 
            substring="visuals/"
            location="${file/$substring/localizations/}"
            substring="/stringresources"
            newLocation="${location/$substring//stringResources}"
            cp $file $newLocation;
          done;
      - name: Commit and push EN translation
        run:
          git add . && git commit -S -m "New translation" >/dev/null && git push || echo "No changes to commit"
      - name: Copy translations
        run: |
          for file in ./visuals/*/stringResources/*/resources.resjson; do 
            substring="visuals/"
            location="${file/$substring/localizations/}"
            # substring="/stringresources"
            # oldFile="${location/$substring//stringResources}"
            cp $location $file;
          done;
      - name: Commit and push new changes to repos
        run: |
          mainFolder=$PWD
          for folder in visuals/*; do
            repoName=$(echo $folder| cut -d'/' -f 2)
            cd "$mainFolder/$folder"
            defaultBranchName=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
            git add . && git commit -S -m "New translations" >/dev/null && \
              (git push --force origin new-translations || git push --set-upstream origin new-translations) &&
              gh pr create -B "$defaultBranchName" -b "Auto created" -t "New translations" || \
              echo "No changes for $repoName"
          done;
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}