on: push

jobs:
  update_translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: 'true'
      - name: Update submodules
        run: 
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Copy EN translation
        run: |
          for file in ./visuals/*/stringResources/en-US/resources.resjson; do 
            substring="visuals/"
            location="${file/$substring/localizations/}"
            substring="/stringresources"
            newLocation="${location/$substring//stringResources}"
            cp $file $newLocation;
          done;
      - name: Commit and push EN translation
        run: git add . & git commit "new EN translation" & git push
      - name: Copy translations
        run: |
          for file in ./visuals/*/stringResources/*/resources.resjson; do 
            substring="visuals/"
            location="${file/$substring/localizations/}"
            substring="/stringresources"
            oldFile="${location/$substring//stringResources}"
            cp $oldFile $file;
          done;
      - name: Commit and push new changes to repos
        run: |
          mainFolder=$PWD
          for folder in visuals/*; do
            cd $mainFolder/$folder;
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
          done;