on: push

jobs:
  update_translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Update submodules
        run: 
          git submodule update
      - name: Copy EN translation
        run: |
          for file in ./visuals/*/stringResources/en-US/resources.resjson; do 
            substring="visuals/"
            location="${file/$substring/localizations/}"
            substring="/stringresources"
            newLocation="${location/$substring//stringResources}"
            cp $file $newLocation;
          done;
      - name: Commit and push EN translation
        run: |
          git config --global user.name 'pbicvbot'
          git config --global user.email 'pbicvbot@microsoft.com'
          git remote set-url origin https://x-access-token:microsoft@github.com/${{ github.repository }}
          git commit -am "New translation" && git push || echo "No changes to commit"
      - name: Copy translations
        run: |
          for file in ./visuals/*/stringResources/*/resources.resjson; do 
            substring="visuals/"
            location="${file/$substring/localizations/}"
            substring="/stringresources"
            oldFile="${location/$substring//stringResources}"
            cp $oldFile $file;
          done;
      - name: Commit and push new changes to repos
        run: |
          git config --global user.name 'pbicvbot'
          git config --global user.email 'pbicvbot@microsoft.com'
          mainFolder=$PWD
          for folder in localizations/*; do
            repoName=$(echo $folder| cut -d'/' -f 2)
            cd $mainFolder/localizations/repoName;
            git remote set-url origin https://x-access-token:microsoft@github.com/$repoName
            git commit -am "New translations" && git push origin HEAD:master || echo "No changes to commit"
          done;